# --- Build Stage ---
    FROM node:20-alpine AS builder

    WORKDIR /app
    
    # Install dependencies
    COPY package*.json ./
    RUN npm install
    
    # Copy source files and build
    COPY . .
    RUN npm run build
    
    
    # --- Runtime Stage ---
    FROM node:20-alpine AS runner
    
    WORKDIR /app
    
    # Only copy necessary files
    COPY --from=builder /app/package*.json ./
    COPY --from=builder /app/node_modules ./node_modules
    COPY --from=builder /app/.next .next
    COPY --from=builder /app/public ./public
    COPY --from=builder /app/next.config.js ./
    
    # Optional: MikroORM config & entities
    COPY --from=builder /app/mikro-orm.config.cjs ./
    COPY --from=builder /app/dist ./dist
    COPY --from=builder /app/migrations ./migrations
    COPY --from=builder /app/app ./app
    
    
    EXPOSE 3000
    ENV NODE_ENV=production
    
    CMD ["npm", "start"]
    